print('Esophagus')
print('Habang tayo ay kumakain sa hapag')
print('...')
print('Esophagus')
print('Habang tayo ay kumakain sa hapag')
print('...')
print('Esophagus')
print('Habang tayo ay kumakain sa hapag')
print('...')
print('Esophagus')
print('Habang tayo ay kumakain sa hapag')
print('...')
